var tid = "";
var aid = "";
var uin = "";
var key = "";
var biz = "MjM5ODgxOTUyMQ==";
var mid = "201586979";
var idx = "1";
var itemidx = "";
var nickname = "哈师大助手";
var user_name = "gh_b315c2abe8ce";
var fakeid = "";
var version = "";
var is_limit_user = "0";
var msg_title = "";
var msg_desc = "";
var msg_cdn_url = "";
var msg_link = "";
var msg_source_url = '';
var networkType;
var appmsgid = '' || '201586979';
var abtest = 0;
var readNum = 1;
var likeNum = '赞';
var appuin = "MjM5ODgxOTUyMQ==";
var source = "";
var scene = 75;
var ct = "1420464436";
var user_uin = "0" * 1;
var comment_id = "0" * 1;
var svr_time = "" * 1;
var comment_enabled = "" * 1;
var devicetype = "";
var pass_ticket = "";
var sn = "f1cc7ca31e20400c4ef4cfc5b1e369df";

seajs.use("appmsg/index.js");